### ISSUE TITLE
Putting code in header files

### ISSUE THREAD

**Issue by darrylb123** [Lupo135/ESP32_SMA-Inverter#2]
I submitted a pull request to remove the code from the header files and create .ino files for the code.
It is poor practice to put code in headers which should only be for definitions.

Please review my pull request to show how refactoring the code into .ino and .h files could be achieved.

I would be happy to assist as i am interested in your good work.

**Comment by Lupo135** [comment]
1. You are right that having code within header files is not a good practice. But it is done on many Arduino projects. I want to include most of this code into an other private project with electricity meter and heating controller. So I prefere to have a low file count.

2. I'm inexperienced in handling git. I have no idea how to add your pull request to my project.

**Comment by darrylb123** [comment]
#2 I'm not all that across git & GitHub but I have a project that gets pull
requests. This is what I do.
- to create a pull request they fork the code and it is placed in their
account.
- they make changes to their version and push it to their version
- they create a pull request that asks to pull their changes into your repo

That works fine if you have not made changes in the mean time. If you're
has moved too, you may attempt a merge via GitHub or you can manually merge.

For example, you added a lot more code after I created the pull request so
the merge is likely quite difficult. If you hadn't made changes and you
wanted to maybe merge my pull request:

- Clone my fork
- Look at the changes to see if you agree
- compile /test it etc
- if you're happy with it, you go to the pull request in GitHub and click
the merge button.
- you then go to your local repo and perform a git pull to update your
local with the changes.

**Comment by darrylb123** [comment]
My intention is to use your code and add a few things ( if you haven't
already):
- wifi configuration via Esptouch smart config. Very simple to incorporate
and works very well.
- web page to set the Bluetooth address of the inverter and any other
settings.
- web page to display current values
- mqtt client to send the values into home assistant

**Comment by Lupo135** [comment]
A simple webpage with current values is already implemented in the latest version. But there are a lot of things to improve stability in the communication.
1. handle error cases: e.g. connect and logon again, when the communication fails.
2. detect and handle shutdown and wakeup of the inverter
3. store power values for the whole day and store manny days in file system and display in a xy diagram. This I do already on the values for my electricity meter.
4. reduce the footprint of the code. Currently I have the problem that it does not fit together with OTA into the 4KByte Flash of the ESP32. Mayby I have to move to a 8 or 16KB flash.

**Comment by darrylb123** [comment]
Perhaps target esp32 board with sdcard for storage. I see there are a few
with built in SD cards available.
Use mqtt for external storage otherwise?

**Comment by habuild** [comment]
You may have found this already. You can pick the partitions etc. The default ones are small.

https://rntlab.com/question/text-section-exceeds-available-space-in-board/
It is around the 5th post.

Hi.
Check your Arduino IDE settings on the following:

Tools > Flash size
Tools > Partition scheme

I was able to finally get your code to fit by adjusting my partitions. 
pops up a nice webpage with countdown. 


Also line around 166 in SMA_inverter.h
needs a bracket and possibly push or pull? it works with push

```
this
#pragma pack 1
should be
#pragma pack (1)
or possibly this 
#pragma pack (push, 1)
```

OOO and efficiency calc is incorrect. At least it wrong for my inverter. it outs between 200% and 700% for me.
It is usually under 100% from SBFspot for me.

the only reference I could find to the calc is

https://github.com/SBFspot/SBFspot/issues/104

```
float calEfficiency = inverters[inv]->calPdcTot == 0 ? 0 : (float)inverters[inv]->TotalPac / (float)inverters[inv]->calPdcTot * 100.0;
```

**Comment by Lupo135** [comment]
Hi,
I have ESP32 with 4Mbyte flash and use "No OTA 2M App/2M SPIFF" partition scheme.
I will correct the #pragma issue on the next version. But this can take some time, because I'm working to get  achieve day data from the inverter and need to test some time.
I could not understand the problem with efficiency calculation. Maybe there is an overflow.
